"""Convert our existing trace corpus to a LeRobot dataset with absolute joint actions.

Our corpus (HF: arif101/openpi-contact-mpc-2026-05-19, folder
recovery_source_traces/) was generated by Pi0.5 on LIBERO and contains
full joint qpos at every step plus the original 7-dim EE-delta action.

For absolute-joint training, the action at step t becomes:
    action[:7] = q(t + H)  # 7 arm joint positions H steps ahead
    action[7]  = grip_cmd(t)  # original gripper command (unchanged)

H = action chunk horizon (default 10 for Pi0.5).

If t + H exceeds trajectory length, pad with the last joint state.

Output: LeRobot dataset with action shape (8,) — pure absolute joint
position targets + gripper command. Drop-in replacement for the
EE-delta dataset, ready to BC-fine-tune Pi0.5 against.

Usage:
  # On GPU box with traces downloaded from HF
  uv run python3 scripts/convert_traces_to_absolute_joint_lerobot.py \\
      --traces-dir data/contact_mpc/recovery_source_traces \\
      --repo-name arif101/libero_absolute_joint_smoke \\
      --horizon 10 \\
      --filter-task 3 \\
      --only-ok
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

import numpy as np


def find_drawer_joints_etc(qpos_shape: int) -> int:
    """Robot is the first 7 qpos slots in LIBERO (Franka Panda)."""
    return 7


def relabel_episode(d, horizon: int = 10) -> dict:
    """Re-label a trace's actions from EE-delta to absolute-joint-at-t+H.

    Returns dict with arrays: image, wrist_image, state (8,), action (8,).
    Each row is one frame; the last `horizon-1` frames have padded actions.
    """
    qpos = d["qpos"]              # (T, n_q)
    ee_pos = d["ee_pos"]          # (T, 3)
    ee_quat = d["ee_quat"]        # (T, 4)
    gq = d["gripper_qpos"]        # (T, 2 or 1)
    act_orig = d["action"]        # (T, 7) -- EE-delta + grip
    img = d["image"]              # (T_img, H, W, C) — stride-sampled
    img_t = d["image_t"]          # (T_img,) — global step idx for each image
    wrist = d["wrist_image"]      # (T_img, H, W, C)
    T = act_orig.shape[0]
    n_joint = find_drawer_joints_etc(qpos.shape[1])

    # 8-dim state per step: [ee_pos(3), ee_quat(4), grip(1)]
    grip_state = gq[:, :1] if gq.ndim == 2 else gq.reshape(T, 1)
    state = np.concatenate([ee_pos, ee_quat, grip_state], axis=1).astype(np.float32)

    # 8-dim absolute joint action: [q(t+H)[:7], grip_cmd(t)]
    new_action = np.zeros((T, 8), dtype=np.float32)
    for t in range(T):
        tgt = min(t + horizon, T - 1)
        new_action[t, :n_joint] = qpos[tgt, :n_joint].astype(np.float32)
        new_action[t, n_joint] = act_orig[t, -1]  # gripper command (last dim)

    # Map images: only frames where we have image data (stride 10 typically)
    # For BC we need image at every step. We tile the closest available image
    # forward in time, matching how Cosmos-RL exposes images during inference.
    full_img = np.zeros((T, *img.shape[1:]), dtype=img.dtype)
    full_wrist = np.zeros((T, *wrist.shape[1:]), dtype=wrist.dtype)
    last_idx = 0
    for t in range(T):
        # Find the most recent image_t <= t
        while last_idx + 1 < len(img_t) and img_t[last_idx + 1] <= t:
            last_idx += 1
        full_img[t] = img[last_idx]
        full_wrist[t] = wrist[last_idx]

    task = str(d.get("task_description", ""))
    return {
        "image": full_img,
        "wrist_image": full_wrist,
        "state": state,
        "action": new_action,
        "task": task,
    }


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--traces-dir", required=True)
    p.add_argument("--repo-name", default="arif101/libero_absolute_joint_smoke")
    p.add_argument("--horizon", type=int, default=10,
                   help="Action chunk horizon: q(t+H) is the target")
    p.add_argument("--filter-task", type=int, default=None,
                   help="Only convert traces with this task index (e.g. 3)")
    p.add_argument("--only-ok", action="store_true",
                   help="Only convert PHYS_OK traces (skip failures for BC)")
    p.add_argument("--limit", type=int, default=None)
    p.add_argument("--push-to-hub", action="store_true")
    p.add_argument("--out-dir", default=None,
                   help="Local LeRobot output dir; defaults to $HF_LEROBOT_HOME/<repo-name>")
    return p.parse_args()


def main() -> int:
    args = parse_args()

    # Lazy import — try modern path first, then old
    try:
        from lerobot.datasets.lerobot_dataset import HF_LEROBOT_HOME, LeRobotDataset
    except ImportError:
        try:
            from lerobot.common.datasets.lerobot_dataset import HF_LEROBOT_HOME, LeRobotDataset
        except ImportError:
            print("ERROR: lerobot not installed. uv pip install lerobot")
            return 1
    import shutil

    repo_name = args.repo_name
    output_path = pathlib.Path(args.out_dir) if args.out_dir else HF_LEROBOT_HOME / repo_name
    if output_path.exists():
        print(f"Removing existing {output_path}")
        shutil.rmtree(output_path)

    # Pull a sample trace to discover image shape
    traces_dir = pathlib.Path(args.traces_dir)
    pattern = "PHYS_OK_*.npz" if args.only_ok else "PHYS_*.npz"
    if args.filter_task is not None:
        pattern = f"PHYS_OK_libero_10_task{args.filter_task}_*.npz" if args.only_ok else f"PHYS_*libero_10_task{args.filter_task}_*.npz"
    paths = sorted(traces_dir.glob(pattern))
    if args.limit:
        paths = paths[:args.limit]
    if not paths:
        print(f"No traces matched {pattern} in {traces_dir}")
        return 1
    sample = np.load(paths[0], allow_pickle=True)
    h, w, c = sample["image"].shape[1:]
    print(f"Image shape: {h}x{w}x{c}, found {len(paths)} traces")

    dataset = LeRobotDataset.create(
        repo_id=repo_name,
        robot_type="panda",
        fps=10,
        features={
            "image": {"dtype": "image", "shape": (h, w, c), "names": ["height", "width", "channel"]},
            "wrist_image": {"dtype": "image", "shape": (h, w, c), "names": ["height", "width", "channel"]},
            "state": {"dtype": "float32", "shape": (8,), "names": ["state"]},
            "actions": {"dtype": "float32", "shape": (8,), "names": ["actions"]},
        },
        image_writer_threads=10,
        image_writer_processes=5,
    )

    n_episodes = 0
    n_frames_total = 0
    for p in paths:
        try:
            d = np.load(p, allow_pickle=True)
            ep = relabel_episode(d, horizon=args.horizon)
        except Exception as e:
            print(f"  SKIP {p.name}: {type(e).__name__}: {e}")
            continue
        T = ep["state"].shape[0]
        for t in range(T):
            dataset.add_frame({
                "image": ep["image"][t],
                "wrist_image": ep["wrist_image"][t],
                "state": ep["state"][t],
                "actions": ep["action"][t],
                "task": ep["task"],
            })
        dataset.save_episode()
        n_episodes += 1
        n_frames_total += T
        if n_episodes % 10 == 0:
            print(f"  {n_episodes} episodes, {n_frames_total} frames")
    print(f"\nDone: {n_episodes} episodes, {n_frames_total} frames")
    print(f"Output: {output_path}")

    if args.push_to_hub:
        dataset.push_to_hub(
            tags=["libero", "panda", "absolute-joint"],
            private=True,
            license="apache-2.0",
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
